#!/bin/bash
# This script generates source code for each stage (aka version)
# using AMLEO: http://opengamestudio.org/amleo

DIR=`dirname $0`
GEN=amleo.py

# 01.Tool.
$GEN $DIR/01*/{cfg,t,v}
# 02.?.
#$GEN $DIR/02*/{cfg,t} $DIR/0{1,2}*/v
